# Generated by Django 4.2.8 on 2023-12-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CairoCoin', '0003_bankrate_bhd_bankrate_gbp_bankrate_jod_bankrate_omr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrate',
            name='bhd',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bankrate',
            name='gbp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bankrate',
            name='jod',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bankrate',
            name='omr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='blackmarket2',
            name='bhd2egp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='blackmarket2',
            name='gbp2egp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='blackmarket2',
            name='jod2egp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='blackmarket2',
            name='omr2egp',
            field=models.FloatField(),
        ),
    ]
